### ISSUE TITLE
Text unreadable when creating Post or replying in a thread

### ISSUE THREAD

**Issue by tsuliwaensis** [jszklarz-haventec/makeitdark#13]
When creating a post, the text color is set to black so it's nearly impossible to create one. Also, when starting or replying to a thread, the text is white on a white background so you have the same issue.

**Comment by LostConnection** [comment]
@tsuliwaensis Is the issue for starting a thread/replying to a thread related to the All Threads tab styling issues mentioned in [this issue](https://github.com/LostConnection/makeitdark/issues/14) or is this something else? If it's not related could you provide a screenshot?

For the post issue, for me the post text is dark gray on black which is also unreadable but I think what you are seeing is different from me. Could you also post a screenshot of this please?

**Comment by tsuliwaensis** [comment]
Here's what creating / editing a post looks like for me. The All Threads view looks good now :)

![ScreenShot1](https://user-images.githubusercontent.com/40817465/56087145-94d2ef80-5e2a-11e9-9fc0-9677369a7631.png)

**Comment by LostConnection** [comment]
Ok thanks, will work on a fix for this.

**Comment by LostConnection** [comment]
This should now be fixed in the latest code in master. Could you update with the latest darkreader.css and let me know if it's all ok?
