### ISSUE TITLE
All Threads broken

### ISSUE THREAD

**Issue by turbohappy** [jszklarz-haventec/makeitdark#14]
Seems that something was changed today by Slack that broke the "All Threads" view and everything is blinding white.

**Comment by juuba** [comment]
Came in to say this aswell, here's a picture:

![image](https://user-images.githubusercontent.com/7961613/55699638-570e3b00-59d4-11e9-8c19-9f7be9aca5a1.png)

**Comment by LostConnection** [comment]
Hi I am going to update the css to address this issue.

**Comment by LostConnection** [comment]
@turbohappy @juuba I have merged a fix for this to master. If the issue is fixed for you we can close this.

**Comment by juuba** [comment]
Works for me!

**Comment by LostConnection** [comment]
Great, closing the issue
