### ISSUE TITLE
Slack theme path not found

### ISSUE THREAD

**Issue by ZugBahnHof** [jszklarz-haventec/makeitdark#18]
This is my error message:
```bash
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/slack/resources/app.asar.unpacked/src/static/ssb-interop.js'
```
and this is the whole programm output:
```bash
sudo python3 makeitdark.py 
[sudo] Passwort für lolo: 
Detected linux OS
Traceback (most recent call last):
  File "makeitdark.py", line 94, in <module>
    with open(slack_theme_path, "r+") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/slack/resources/app.asar.unpacked/src/static/ssb-interop.js'
```
I think I have to change the folder for the file. Dos anybody knows, where it could be?

Thank you!

**Comment by LostConnection** [comment]
This could be related to the way you have installed Slack. I believe some installers will put it under a different dir to the one that we expect in the script.
Do you remember how you installed it and I can look into making that dir supported.

**Comment by ZugBahnHof** [comment]
I think I installed the one from the official Ubuntu 19.10 sources (`sudo apt install slack`), but I don't know anymore...

**Comment by tsuliwaensis** [comment]
This is happening with Slack beta 4.0.0. It looks like they removed `ssb-interop.js`. I poked around a bit, but I don't see where the styles are kept in the new version.

**Comment by LostConnection** [comment]
Mm yeah, I see what you mean. Looks like what we want is in the react-devtools, it seems that the embedded react components exist in there. I have only had a very brief look into the beta but will have a more detailed look later.

**Comment by LostConnection** [comment]
This fix will drastically change the script, in that it will entirely remove the javascript code that injects the styles. I'll probably fork into a new repo for Slack 4.0.0 onwards

**Comment by MarissaKWilson** [comment]
I use your script (and I love it!). I added a shell script and updated the python script so it works with Slack 4.0 on Mac OSX. Sharing in case it helps you update your script (this is your repo that I forked) 
https://github.com/MarissaKWilson/makeitdark

This fix requires node and asar as dependencies

**Comment by LostConnection** [comment]
I am closing this as [issue 27](url) is a duplicate
