### ISSUE TITLE
Incorrectly styled segments in Notifications Preferences.

### ISSUE THREAD

**Issue by shwayn3** [jszklarz-haventec/makeitdark#19]
In Preferences > Notifications, you see this:

![image](https://user-images.githubusercontent.com/317358/58779065-0ef84700-8618-11e9-966e-1f36da9c04b0.png)

**Comment by LostConnection** [comment]
This should now be fixed with the latest changes to master. Could you confirm it is fixed by using the lates darkreader.css?

**Comment by shwayn3** [comment]
Confirmed fixed.
