### ISSUE TITLE
No styles applied to Channel Search

### ISSUE THREAD

**Issue by shwayn3** [jszklarz-haventec/makeitdark#20]
When using the new channel search feature, the dark mode styles are not applied, see:

![image](https://user-images.githubusercontent.com/317358/58779161-5b438700-8618-11e9-9919-78cf0ff2f8c1.png)

**Comment by LostConnection** [comment]
This issue should be fixed with the latest styles in master. Could you please confirm using the latest darkreader.css?

**Comment by shwayn3** [comment]
Confirmed fixed.
