### ISSUE TITLE
Temporarily highlighted messages are unreadable for a few moments.

### ISSUE THREAD

**Issue by shwayn3** [jszklarz-haventec/makeitdark#24]
When you click a link to a message, the message is highlighted to draw your attention to the right content, however in this darkmode it becomes very difficult to read the content for a few moments before the fade dies away.

![darkmode](https://user-images.githubusercontent.com/317358/59009386-b8d21080-8870-11e9-9e41-5004532acfbf.png)

Without darkmode the field just goes from white to yellow (still very readable).

**Comment by LostConnection** [comment]
I've changed the highlight to be slightly lighter than the message container background. Master is updated with the new changes.

**Comment by shwayn3** [comment]
Change verified, works well!
