### ISSUE TITLE
Doesn't work on the new Slack version 4.0.0

### ISSUE THREAD

**Issue by yourfriendaaron** [jszklarz-haventec/makeitdark#27]

**Comment by Benhgift** [comment]
Here's a fix for windows: https://www.reddit.com/r/Slack/comments/cesgjb/dont_update_to_the_newest_version_of_slack_no/eu4ujg9/

Now we need to build that into `makeitdark`

**Comment by LostConnection** [comment]
I'm adding a bash script that will handle the new injection. It requires unpacking the app, injecting and then repacking it so it will require node as a dependency.

**Comment by LostConnection** [comment]
I've added the bash substitute for the python script. Works for me so if it works for you we can close this.

**Comment by Gabrinthei** [comment]
Tried to test on Mac, applying the new script seems to have locked slack into an endless loading loop (stuck on splash screen with spinner).

Note - this was testing with master

**Comment by yourfriendaaron** [comment]
Tried on Windows with Git Bash after installing nodejs, didn't work

**Comment by LostConnection** [comment]
> Tried to test on Mac, applying the new script seems to have locked slack into an endless loading loop (stuck on splash screen with spinner).
> 
> Note - this was testing with master



> Tried on Windows with Git Bash after installing nodejs, didn't work

Damn, to fix that you may need to manually remove the appended js in the ssb-interop.bundle.js file.
Mac: /Applications/Slack.app/Contens/Resources/app.asar.unpacked/dist/ssb-interop.bundle.js
Linux: /usr/lib/slack/resources/app.asar.unpacked/dist/ssb-interop.bundle.js
Windows: <Install dir>/slack/<version>/resources/app.asar.unpacked/dist/ssb-interop.bundle.js 

To avoid any further problems I have ported the unpack/repack logic in the shell script to the python script so it will work like before. I've tested most scenarios on my mac but haven't done on any linux or windows machine yet.

Please try the script again using the updated master but keep in mind you will need to install nodejs if you don't have it already as unpacking and packing the app requires npx.

**Comment by yourfriendaaron** [comment]
Getting this while running on Windows 10

`Found app-4.0.0
'sudo' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\Users\MONOLITH\Desktop\makeitdark-master\makeitdark.py", line 124, in <module>
    with open(slack_theme_path, "r+") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\[username]\\AppData\\Local\\slack\\app-4.0.0\\resources/app.asar.unpacked/dist/ssb-interop.bundle.js'`

**Comment by LostConnection** [comment]
Thanks,
I've pushed some changes to account for the sudo logic. Sorry about this, I don't have access to a Windows machine right now and don't have the time to install and run a VM.
Hopefully those changes fix the issue.

**Comment by Gargaj** [comment]
https://github.com/Gargaj/makeitdark/blob/master/makeitdark.py

Does it without having to install node.js

**Comment by Gabrinthei** [comment]
Hell yeah! Working now. Thanks for the awesome script and continual support

**Comment by hioz12** [comment]
Its working! But im getting white while on a thread and the reply box.

![2019-07-25_11-38-09](https://user-images.githubusercontent.com/35497308/61888166-124dd780-aed1-11e9-8d90-8f5577f4de02.png)

**Comment by defmonk0** [comment]
@hioz12 I'd create a new issue. My guess is that the CSS file extracted from darkreader needs to be updated due to changes in some class names in slack (or something similar).

@LostConnection when trying to install on windows, I had an issue with the code assuming the character encoding.

Full output:
```bash
$ py makeitdark.py
npx: installed 21 in 2.36s
Searching for most recent slack update in C:\Users\steve\AppData\Local\slack
Found app-4.0.0
Traceback (most recent call last):
  File "makeitdark.py", line 133, in <module>
    if BEGIN_MARKER in f.read():
  File "C:\Users\steve\AppData\Local\Programs\Python\Python37-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 81033: character maps to <undefined>
```

My guess is certain versions of python on windows assumes [CP1252 encoding](https://en.wikipedia.org/wiki/Windows-1252) by default, instead of the more reasonable defaults on unix-based OSs (UTF-8).

After some [brief googling of the error](https://stackoverflow.com/questions/9233027/unicodedecodeerror-charmap-codec-cant-decode-byte-x-in-position-y-character), I found changing [Line 132](https://github.com/LostConnection/makeitdark/blob/master/makeitdark.py#L132) (and 113 for the uninstall, which I just didn't try) to include the encoding fixed the issue locally.

To be exact, I changed from:
```    with open(slack_theme_path, "r+") as f:```
to:
```    with open(slack_theme_path, "r+", encoding="utf8") as f:```

I don't know if hard-coding it is really the best route to take (I'm not familiar with the mac or linux installs, though it's probably safe to assume slack will always ship those files encoded in UTF-8) so I'll just leave this information to do with as you see fit.

**Comment by Gargaj** [comment]
> https://github.com/Gargaj/makeitdark/blob/master/makeitdark.py
> 
> Does it without having to install node.js

Windows standalone version: https://github.com/Gargaj/makeitdark/releases/download/4.0/makeitdark-win32.zip

**Comment by LostConnection** [comment]
@Gargaj 
> https://github.com/Gargaj/makeitdark/blob/master/makeitdark.py
> 
> Does it without having to install node.js

Very nice, I will have a read =)

@hoiz12 
> Its working! But im getting white while on a thread and the reply box.

Opened [this issue](https://github.com/LostConnection/makeitdark/issues/31)


@defmonk0 
> To be exact, I changed from:
> ` with open(slack_theme_path, "r+") as f:`
> to:
> ` with open(slack_theme_path, "r+", encoding="utf8") as f:`
> 
> I don't know if hard-coding it is really the best route to take (I'm not familiar with the mac or linux installs, though it's probably safe to assume slack will always ship those files encoded in UTF-8) so I'll just leave this information to do with as you see fit.

Looks good. Also feel free to drop a PR =) Otherwise I'll add it.

**Comment by LostConnection** [comment]
> Its working! But im getting white while on a thread and the reply box.
> 
> ![2019-07-25_11-38-09](https://user-images.githubusercontent.com/35497308/61888166-124dd780-aed1-11e9-8d90-8f5577f4de02.png)

Opened [this issue](https://github.com/LostConnection/makeitdark/issues/31)

**Comment by LostConnection** [comment]
> To be exact, I changed from:
> ` with open(slack_theme_path, "r+") as f:`
> to:
> ` with open(slack_theme_path, "r+", encoding="utf8") as f:`
> 
> I don't know if hard-coding it is really the best route to take (I'm not familiar with the mac or linux installs, though it's probably safe to assume slack will always ship those files encoded in UTF-8) so I'll just leave this information to do with as you see fit.

@defmonk0 Looks good. Also feel free to drop a PR =) Otherwise I'll add it.

**Comment by yourfriendaaron** [comment]
Thanks for all your help on this. Crazy that Slack still hasn't done this themselves.

Got this to (mostly) work with @defmonk0's fix. But I'm getting these white bars in the top and bottom now:

![2019-07-25 21 25 39](https://user-images.githubusercontent.com/8637082/61919270-e3605180-af22-11e9-9668-04dd3a0ffb60.png)

**Comment by LostConnection** [comment]
@defmonk0
> To be exact, I changed from:
> ` with open(slack_theme_path, "r+") as f:`
> to:
> ` with open(slack_theme_path, "r+", encoding="utf8") as f:`

I went ahead and added this fix to master.

I guess this issue has now been resolved so I will close it.

**Comment by Gabrinthei** [comment]
Tried with the most recent encoding change and getting:
`Traceback (most recent call last):
  File "./makeitdark.py", line 132, in <module>
    with open(slack_theme_path, "r+", encoding="utf8") as f:
TypeError: 'encoding' is an invalid keyword argument for this function`
