### ISSUE TITLE
Slack update 4.0.1 (productio

### ISSUE THREAD

**Issue by sinewalker** [jszklarz-haventec/makeitdark#37]
might relate to #27 #31 and #32 

In Slack 4.0.1, message box now has a white surrounding.  There's a new section with formatting buttons added by Slack
![Screen Shot 2019-08-15 at 12 20 45](https://user-images.githubusercontent.com/124139/63069107-047ff500-bf59-11e9-88f8-3ea12e9a9d4e.png)

**Comment by Kertic** [comment]
Also having this issue, on a mac here.

**Comment by LostConnection** [comment]
The css on master has been updated with a fix for this. If you are no longer having this problem then I will close this issue :)

**Comment by sinewalker** [comment]
fantastic!  Thanks very much

**Comment by sinewalker** [comment]
commit 60dc853 fixes, you're awesome.
